import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Sidebar } from '@/components/dashboard/Sidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className='fixed flex h-screen overflow-hidden w-full bg-gray-100/40'>
          <Sidebar />
          <div className='h-screen'>
          <div className='flex flex-1 flex-col h-full overflow-scroll p-4 md:gap-8 md:p-6'>
            {children}
          </div>
          </div>
        </main>
      </body>
    </html>
  );
}
